import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { FC, useEffect, useState } from 'react'
import Menu from '../components/Menu'
import Login from '../components/Login'
import { GetServerSideProps } from 'next'

interface HomeProps{
  authtoken:string
}

export const getServerSideProps: GetServerSideProps = async ({req, res})=>{
    const token = req.cookies.authtoken || "";
    return {
      props:{
        authtoken:token
      },
    }
}


export default function Home({authtoken} :HomeProps) {
  const [loggedIn, changeLogInState] = useState<boolean>(false);
  const [user, updateUser] = useState<string>("")
  
  function verifySession(token:string){
    fetch('api/auth/verifySession', {
      method:'POST',
      body:JSON.stringify({
        token:authtoken
      })
    })
    .then(response => {
      if(response.status === 200){
        changeLogInState(true);
        return response.json();
      }else{
        changeLogInState(false);
        updateUser("")
      }
    }).then(res =>{
      updateUser(res.id)
      console.log(res)
    });
  }

  useEffect(()=>{
    verifySession(authtoken)
  },[])

  return (
    <>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          RPS
        </h1>
       {loggedIn? <Menu user={user}></Menu>: <Login></Login>}
      </main>
    </>
  )
}
